# .air.toml
root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ."
bin = "./tmp/main"
exclude_dir = ["assets", "tmp", "vendor"]
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_file = []
exclude_regex = []
follow_symlink = false
delay = 1000 # ms
stop_on_error = true
kill_delay = 500 # ms

[log]
time = true
level = "debug"

[misc]
clean_on_exit = true
