// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: finance.sql

package mydb

import (
	"context"
	"database/sql"
)

const createFinance = `-- name: CreateFinance :exec
INSERT INTO finances (user_id, type, source, amount, date, description)
VALUES ($1, 'income', $2, $3, $4, $5)
`

type CreateFinanceParams struct {
	UserID      int32          `json:"user_id"`
	Source      sql.NullString `json:"source"`
	Amount      sql.NullString `json:"amount"`
	Date        sql.NullTime   `json:"date"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) CreateFinance(ctx context.Context, arg CreateFinanceParams) error {
	_, err := q.db.ExecContext(ctx, createFinance,
		arg.UserID,
		arg.Source,
		arg.Amount,
		arg.Date,
		arg.Description,
	)
	return err
}

const getFinanceForUser = `-- name: GetFinanceForUser :many
SELECT finance_id, user_id, type, source, amount, date, description FROM finances
WHERE type = 'income' AND user_id = $1
`

func (q *Queries) GetFinanceForUser(ctx context.Context, userID int32) ([]Finance, error) {
	rows, err := q.db.QueryContext(ctx, getFinanceForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Finance
	for rows.Next() {
		var i Finance
		if err := rows.Scan(
			&i.FinanceID,
			&i.UserID,
			&i.Type,
			&i.Source,
			&i.Amount,
			&i.Date,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
