// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package mydb

import (
	"database/sql"
)

type Finance struct {
	FinanceID   int32          `json:"finance_id"`
	UserID      int32          `json:"user_id"`
	Type        sql.NullString `json:"type"`
	Source      sql.NullString `json:"source"`
	Amount      sql.NullString `json:"amount"`
	Date        sql.NullTime   `json:"date"`
	Description sql.NullString `json:"description"`
}

type User struct {
	UserID       int32        `json:"user_id"`
	Username     string       `json:"username"`
	PasswordHash string       `json:"password_hash"`
	Email        string       `json:"email"`
	CreatedAt    sql.NullTime `json:"created_at"`
}
