// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
)

type Income struct {
	ID      int32          `json:"id"`
	Income1 sql.NullString `json:"income1"`
	Income2 sql.NullString `json:"income2"`
	Income3 sql.NullString `json:"income3"`
}
